### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by xastronomical** [imaginamundo/deno-ssr-jsx#1]
Would be cool if you add TypeScript support (a single `.d.ts` file is sufficient). I could also submit a PR if you want. Thanks in advance!

**Comment by imaginamundo** [comment]
Hiii, good day!

I would love to see the PR, I have never configured types for deno, would be a good way to learn :D

**Comment by xastronomical** [comment]
Alright cool, I'll start working tomorrow since I'm busy right now.
